// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFivpxWMfRH77uN3WMoKF23E-PEEp21A',
    appId: '1:396499039511:web:af6712fd010b28cd83f352',
    messagingSenderId: '396499039511',
    projectId: 'product-pulse-cc636',
    authDomain: 'product-pulse-cc636.firebaseapp.com',
    storageBucket: 'product-pulse-cc636.appspot.com',
    measurementId: 'G-Z46585T6WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBhDuOQhRTWpMowYAhlDr6mrCrWvkYO5Q',
    appId: '1:396499039511:android:9a5af438e489bc4183f352',
    messagingSenderId: '396499039511',
    projectId: 'product-pulse-cc636',
    storageBucket: 'product-pulse-cc636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzKwYlRN7mW_KwHuBIis3wrG2hkZhsLNo',
    appId: '1:396499039511:ios:b4bf11e3916cb0c283f352',
    messagingSenderId: '396499039511',
    projectId: 'product-pulse-cc636',
    storageBucket: 'product-pulse-cc636.appspot.com',
    iosBundleId: 'com.example.productPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzKwYlRN7mW_KwHuBIis3wrG2hkZhsLNo',
    appId: '1:396499039511:ios:b4bf11e3916cb0c283f352',
    messagingSenderId: '396499039511',
    projectId: 'product-pulse-cc636',
    storageBucket: 'product-pulse-cc636.appspot.com',
    iosBundleId: 'com.example.productPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMFivpxWMfRH77uN3WMoKF23E-PEEp21A',
    appId: '1:396499039511:web:1137a23bef406b0b83f352',
    messagingSenderId: '396499039511',
    projectId: 'product-pulse-cc636',
    authDomain: 'product-pulse-cc636.firebaseapp.com',
    storageBucket: 'product-pulse-cc636.appspot.com',
    measurementId: 'G-DQKFDL8GJ6',
  );
}
